apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web-content
          configMap:
            name: web-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Keycloak Protected Webpage</title>
    </head>
    <body>
      <h1>Welcome! This page is protected by Keycloak.</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 80
  selector:
    app: web
